image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

stages:
  - install_deps
  - prebuild
  - build
  - check
  - deploy

# install_deps stage
install_npm_deps:
  stage: install_deps
  needs: []
  script:
    - unset NODE_ENV
    - npm ci --cache .npm --prefer-offline --unsafe-perm=true --allow-root --loglevel verbose

install_compile_map_json:
  stage: install_deps
  needs: []
  script:
    - wget https://gitlab.com/wchs-map/indoor-map-lib/-/jobs/artifacts/master/raw/target/release/compile_map_json?job=build -O compile_map_json
    - chmod +x compile_map_json
  artifacts:
    paths:
      - compile_map_json

# prebuild stage
compile_map_json:
  stage: prebuild
  needs: [install_npm_deps, install_compile_map_json]
  script:
    - export PATH="$PATH:./"
    - npm run compileMapJson
  artifacts:
    paths:
      - src/data/map_compiled.json

# build stage
build:
  stage: build
  needs: [install_npm_deps, compile_map_json]
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

doc:
  stage: build
  # tsdoc freaks out if it can't find map_compiled.json
  needs: [install_npm_deps, compile_map_json]
  script:
    - npm run doc
  artifacts:
    paths:
      - docs/

code_navigation:
  stage: build
  image: sourcegraph/lsif-node:v0.6
  needs: [install_npm_deps, compile_map_json]
  allow_failure: true
  script:
    - lsif-node -p .
  artifacts:
    reports:
      lsif: dump.lsif

# Check stage
lint:
  stage: check
  needs: [install_npm_deps]
  script:
    - npm run lint

test:
  stage: check
  needs: [install_npm_deps]
  script:
    - npm run test-ci
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml

# Deploy stage
deploy-app:
  stage: deploy
  script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no -r dist/* gitlab@54.39.146.11:/var/www/wchs.nvarner.me/public_html
  artifacts:
    paths:
      - dist
  only:
    - master

# deploy docs (called pages so docs end up on GitLab Pages)
pages:
  stage: deploy
  script:
    - mv docs/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
