image: node:12

pages:
  stage: deploy
  script:
  - wget https://gitlab.com/wchs-map/indoor-map-lib/-/jobs/artifacts/master/raw/target/release/compile_map_json?job=build -O compile_map_json
  - chmod +x compile_map_json
  - export PATH="$PATH:./"
  - npm install --unsafe-perm=true --allow-root --loglevel verbose
  - npm run compileMapJson
  - npm run build
  - mv dist public
  - apt-get update -qq && apt-get install -y -qq sshpass
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no -r public/* gitlab@54.39.146.11:/var/www/wchs.nvarner.me/public_html
  artifacts:
    paths:
    - public
  only:
  - master
